version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `src/UI` directory
    directory: "/src/UI"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Assign reviewers
    reviewers:
      - "team-leads"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "automated"
    # Specify version update preferences
    versioning-strategy: auto
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Group minor and patch updates
    groups:
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the repository root
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for version updates
    labels:
      - "docker"
      - "dependencies"
      - "automated"
    # Allow up to 5 open pull requests for Docker dependencies
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the default location
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for version updates
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
    # Allow up to 5 open pull requests for GitHub Actions
    open-pull-requests-limit: 5 